# Generated by Django 5.1.6 on 2025-02-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otlk_micro', '0002_alter_event_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='outlook_user',
        ),
        migrations.AlterField(
            model_name='outlookuserdata',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='outlookuserdata',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outlookuserdata',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
